from pages import CheckoutPage
from pages.LoginPage import LoginPage
from pages.ProductPage import ProductPage
from test.BaseTest import BaseTest
import time
from pages.CheckoutPage import CheckoutPage
class TestCheckout(BaseTest):

    def test_checkout_with_valid_data(self):
        login_page = LoginPage(self.driver)
        login_page.login_to_homepage("standard_user", "secret_sauce")
        product_page = ProductPage(self.driver)
        assert product_page.display_status_of_page()
        product_page.add_to_cart_button()
        product_page.cart_icon()
        checkout_page = CheckoutPage(self.driver)
        checkout_page.checkout_btn()
        checkout_page.your_information()
        checkout_page.checkout_information("Nikita","Rathor","123456")
        # checkout_page.enter_first_name("Nikita")
        # checkout_page.enter_last_name("Rathor")
        # checkout_page.enter_zip_code("123456")
        checkout_page.continue_btn()

    def test_checkout_with_firstname_blank(self):
        login_page = LoginPage(self.driver)
        login_page.login_to_homepage("standard_user", "secret_sauce")
        product_page = ProductPage(self.driver)
        assert product_page.display_status_of_page()
        product_page.add_to_cart_button()
        product_page.cart_icon()
        checkout_page = CheckoutPage(self.driver)
        checkout_page.checkout_btn()
        checkout_page.your_information()
        checkout_page.checkout_information("","Rathor","123456")
        # checkout_page.enter_first_name("")
        # checkout_page.enter_last_name("Rathor")
        # checkout_page.enter_zip_code("123456")
        checkout_page.continue_btn()
        checkout_page.details_is_required_assert()

    def test_checkout_with_lastname_blank(self):
        login_page = LoginPage(self.driver)
        login_page.login_to_homepage("standard_user", "secret_sauce")
        product_page = ProductPage(self.driver)
        assert product_page.display_status_of_page()
        product_page.add_to_cart_button()
        product_page.cart_icon()
        checkout_page = CheckoutPage(self.driver)
        checkout_page.checkout_btn()
        checkout_page.your_information()
        checkout_page.checkout_information("Nikita","","123456")
        # checkout_page.enter_first_name("Nikita")
        # checkout_page.enter_last_name("")
        # checkout_page.enter_zip_code("123456")
        checkout_page.continue_btn()
        checkout_page.details_is_required_assert()

    def test_checkout_with_postalcode_blank(self):
        login_page = LoginPage(self.driver)
        login_page.login_to_homepage("standard_user", "secret_sauce")
        product_page = ProductPage(self.driver)
        assert product_page.display_status_of_page()
        product_page.add_to_cart_button()
        product_page.cart_icon()
        checkout_page = CheckoutPage(self.driver)
        checkout_page.checkout_btn()
        checkout_page.your_information()
        checkout_page.checkout_information("Nikita","Rathor","")
        # checkout_page.enter_first_name("Honey")
        # checkout_page.enter_last_name("Rathor")
        # checkout_page.enter_zip_code("")
        checkout_page.continue_btn()
        checkout_page.details_is_required_assert()

    def test_checkout_with_cancel_btn(self):
        login_page = LoginPage(self.driver)
        login_page.login_to_homepage("standard_user", "secret_sauce")
        product_page = ProductPage(self.driver)
        assert product_page.display_status_of_page()
        product_page.add_to_cart_button()
        product_page.cart_icon()
        checkout_page = CheckoutPage(self.driver)
        checkout_page.checkout_btn()
        checkout_page.your_information()
        checkout_page.checkout_information("Nikita","Rathor","123456")
        checkout_page.cancel_btn()
        checkout_page.your_cart()
    
    def test_checkout_with_blank_data(self):
        login_page = LoginPage(self.driver)
        login_page.login_to_homepage("standard_user", "secret_sauce")
        product_page = ProductPage(self.driver)
        assert product_page.display_status_of_page()
        product_page.add_to_cart_button()
        product_page.cart_icon()
        checkout_page = CheckoutPage(self.driver)
        checkout_page.checkout_btn()
        checkout_page.your_information()
        checkout_page.checkout_information("","","")
        # checkout_page.enter_first_name("")
        # checkout_page.enter_last_name("")
        # checkout_page.enter_zip_code("")
        checkout_page.continue_btn()
        checkout_page.details_is_required_assert()